import { Subject } from 'rxjs/Subject';
export declare class Tilemap {
    private node;
    private mapConfig;
    private loader;
    private tiles;
    private width;
    private height;
    private isReady;
    private context;
    private isMobile;
    private camera;
    private additionalImages;
    private startX;
    private startY;
    private resizeHandler;
    private ready;
    private click;
    private showTiles;
    private tilesLoader;
    private options;
    constructor(canvasId: string, pathToConfig: string, options: any);
    private getCanvasSize();
    private setCanvasSize();
    private setEvents();
    private draw();
    private drawGrid(tile);
    private getConfig(url, callback);
    private loadImage(callback);
    private getPositionPerNumber(n, tileset);
    private createTiles();
    private init(pathToConfig);
    private sendShowTiles();
    private tilesFilter(tiles);
    private isAllLoaded();
    private resize();
    readonly readyEvent: Subject<any>;
    readonly clickEvent: Subject<any>;
    readonly showTilesEvent: Subject<any>;
    readonly tilesLoaderEvent: Subject<any>;
    moveTo(indexX: number, indexY: number): void;
    setLayerToTile(options: any): void;
    destroy(): void;
}
